---
name: CI

on:
  pull_request:
    branches: ['main', 'dev']
    types: ['opened', 'reopened', 'synchronize']

jobs:
  docker-build:
    name: Check Docker Build
    runs-on: ubuntu-latest
    env:
      DB_PORT: 5432
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker-compose up --build --force-recreate -d app
  project-build:
    name: Build Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint files
        run: pnpm lint:all
      - name: Check TypeScript
        run: pnpm lint:types
      - name: Test files
        run: pnpm test:cov
      - name: Build project
        run: pnpm prebuild && pnpm build
